[project]
name = "ems-meteogate-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "anyio>=4.8.0",
    "pandas>=2.2.3",
    "aiomqtt>=2.5.1",
]

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
